[tool.poetry]
name = "uqcsbot"
version = "0.1.0"
description = "UQCSbot is a chat bot built in Python for the UQCS Discord server."
authors = ["UQ Computing Society <contact@uqcs.org.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = "^1.7.3"
icalendar = "^4.0"
"python-dateutil" = "^2.8"
pytz = "^2021.1"
requests = "^2.25"
beautifulsoup4 = "^4.9"
APScheduler = "^3.7.0"
SQLAlchemy = {version = "^1.4.21", extras = ["postgresql_psycopg2binary"]}
humanize = "^3.11.0"
aiohttp = "^3.7"
emoji = "^1.7.0"
pytest-datafiles = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
