[tool.poetry]
name = "uqcsbot"
version = "0.1.0"
description = "UQCSbot is a chat bot built in Python for the UQCS Discord server."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "^1.7.2"
icalendar = "^4.0"
"python-dateutil" = "^2.8"
pytz = "^2021.1"
requests = "^2.25"
beautifulsoup4 = "^4.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
