name: Code Style Check

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run black
        id: runBlack
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./uqcsbot"
          version: "22.3.0"
      - name: Convert logs to artifacts
        uses: actions/upload-artifact@v3
        if: always() && (steps.runBlack.outcome == 'failure')
        with:
          name: "black-logs"
          path: "/tmp/blk_*"